### PR TITLE
Configures throttling as part of perf test run

### PR DESCRIPTION
**Pull request by mtlynch**
Adds commands to explicitly enable packet shaping on the meddlebox before
every run of the run.yml playbook so that tests run under a defined network
speed limit.

Also changes the archive and log name schema so that the meddlebox throttling
settings are saved as part of the output archive of tests.

---

This change is [Reviewable](https://reviewable.io/reviews/m-lab/ndt-e2e-ansible/23)

### CODE REVIEW

**Comment by nkinkade** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

_[run.yml, line 12 [r1]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/23#-KJkNS1QokABSNlrdDji:-KJkNS1QokABSNlrdDjj:790828675) ([raw file](https://github.com/m-lab/ndt-e2e-ansible/blob/ea935288b5df8a375a492439cf6328a4961ae31c/run.yml#L12)):_

> ``` YAML
>     - name: define meddlebox traffic shaping policy
>       set_fact:
>         shaping_policy: htb
> ```

I thought we had more or less [settled on TFB](https://docs.google.com/document/d/1WL6_XViCpvAb7mwzeIuUL3mJGRLpdqT4Ibl6vfElIVM/edit#heading=h.hhweh1xll899) over HTB qdisc because it introduced less latency?  If we want to allow an option to use either HTB or TFB, then these definitions might need to change because the rule syntax for the two are so different.

---

_[run.yml, line 16 [r1]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/23#-KJkO8AggSg-HYQL2DWH:-KJkO8AggSg-HYQL2DWI:1927312620) ([raw file](https://github.com/m-lab/ndt-e2e-ansible/blob/ea935288b5df8a375a492439cf6328a4961ae31c/run.yml#L16)):_

> ``` YAML
>     - name: define meddlebox traffic shaping policy
>       set_fact:
>         shaping_params: rate {{ throttle_mbps }}mbit
> ```

Could we get rid of the block altogether and just use {{ throttle_mbps }} by itself in "Configure meddlebox for testing" below? "rate" never changes, whether we are using HTB or TFB, and I suspect we will never use another unit other than "mbit", so those two can probably be hard coded into anything else, right?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/23)_

**Comment by mtlynch** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

_[run.yml, line 12 [r1]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/23#-KJkNS1QokABSNlrdDji:-KJk_MrKfyxKf6GSTGvS:-1322231329) ([raw file](https://github.com/m-lab/ndt-e2e-ansible/blob/ea935288b5df8a375a492439cf6328a4961ae31c/run.yml#L12)):_
<details><summary>

<i>Previously, nkinkade wrote…</i></summary>



> I thought we had more or less [settled on TFB](https://docs.google.com/document/d/1WL6_XViCpvAb7mwzeIuUL3mJGRLpdqT4Ibl6vfElIVM/edit#heading=h.hhweh1xll899) over HTB qdisc because it introduced less latency?  If we want to allow an option to use either HTB or TFB, then these definitions might need to change because the rule syntax for the two are so different.
> </details>
> TBF solves the latency problem, but then seemed to screw up throughput numbers. Throttled to 100 Mbps, on OSX+Firefox+Banjo, it gave median readings of 95.2 Mbps down / 74.55 Mbps up and on OSX + Chrome + Banjo it was 87.25 / 91.25.

My plan was to do HTB for the time being and just take the hit on inaccurate latency, then switch to a DPDK-based solution when we want more precision.

---

_[run.yml, line 16 [r1]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/23#-KJkO8AggSg-HYQL2DWH:-KJkaGXuf0vzZdbhYXKI:-19128846) ([raw file](https://github.com/m-lab/ndt-e2e-ansible/blob/ea935288b5df8a375a492439cf6328a4961ae31c/run.yml#L16)):_
<details><summary>

<i>Previously, nkinkade wrote…</i></summary>



> Could we get rid of the block altogether and just use {{ throttle_mbps }} by itself in "Configure meddlebox for testing" below? "rate" never changes, whether we are using HTB or TFB, and I suspect we will never use another unit other than "mbit", so those two can probably be hard coded into anything else, right?
> </details>
> I think you're right and the behavior you're describing is more desirable, but this one's a bit tricky and I can't think of a good way of doing this.

I want the user to be able to set the throughput with just a number (e.g. `--extra-vars "throttle_mbps=50"`). Then two tasks need access to that number: the output filename creation task and the meddlebox configuration task. I can't figure out a way for those two tasks to share the same variable/fact unless we do something like:

``` yaml
- name: define meddlebox traffic shaping throughput as a fact
   set_fact:
     throttle_mbps_fact: "{{ throttle_mbps }}"
```

Do you have ideas about any other way we can achieve this?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/23)_

**Comment by nkinkade** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

_[run.yml, line 16 [r1]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/23#-KJkO8AggSg-HYQL2DWH:-KJkg72XhekOGFy5nz_Y:2012669559) ([raw file](https://github.com/m-lab/ndt-e2e-ansible/blob/ea935288b5df8a375a492439cf6328a4961ae31c/run.yml#L16)):_
<details><summary>

<i>Previously, mtlynch (Michael Lynch) wrote…</i></summary>



> I think you're right and the behavior you're describing is more desirable, but this one's a bit tricky and I can't think of a good way of doing this.
> 
> I want the user to be able to set the throughput with just a number (e.g. `--extra-vars "throttle_mbps=50"`). Then two tasks need access to that number: the output filename creation task and the meddlebox configuration task. I can't figure out a way for those two tasks to share the same variable/fact unless we do something like:
> 
> ``` yaml
> - name: define meddlebox traffic shaping throughput as a fact
>    set_fact:
>      throttle_mbps_fact: "{{ throttle_mbps }}"
> ```
> 
> Do you have ideas about any other way we can achieve this?
> </details>
> Do we even need `shaping_collapsed`? Could we just have something like:

`archive_file: ndt-results-{{ hostname }}-{{  throttle_mbps }}Mbps-{{ datetime }}.zip`

I don't think need the word "rate" in there, since "mbps" is pretty self-explanatory for rate. And I'm not even sure we need `shaping_policy` since we plan to use DPDK soon anyway. Then the configuration of the meddlebox, for now, becomes something like:

```
 tc qdisc add dev {{ item }} root handle 1: htb default 1 && \
 tc class add dev {{ item }} parent 1: classid 1:1 htb rate {{ throttle_mbps }}mbit
```

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/23)_

**Comment by mtlynch** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

_[run.yml, line 16 [r1]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/23#-KJkO8AggSg-HYQL2DWH:-KJkjF_UWhJrq3YSGw_x:-2058049269) ([raw file](https://github.com/m-lab/ndt-e2e-ansible/blob/ea935288b5df8a375a492439cf6328a4961ae31c/run.yml#L16)):_
<details><summary>

<i>Previously, nkinkade wrote…</i></summary>



> Do we even need `shaping_collapsed`? Could we just have something like:
> 
> `archive_file: ndt-results-{{ hostname }}-{{  throttle_mbps }}Mbps-{{ datetime }}.zip`
> 
> I don't think need the word "rate" in there, since "mbps" is pretty self-explanatory for rate. And I'm not even sure we need `shaping_policy` since we plan to use DPDK soon anyway. Then the configuration of the meddlebox, for now, becomes something like:
> 
> ```
>  tc qdisc add dev {{ item }} root handle 1: htb default 1 && \
>  tc class add dev {{ item }} parent 1: classid 1:1 htb rate {{ throttle_mbps }}mbit
> ```
> 
> </details>
> Right, the thing I'm stuck on is how we share the variable across two separate plays. As far as I know, the only way to do that is by using a variable to create a fact.

In the solution you're proposing, would `throttle_mbps` be a variable in the `"Configure meddlebox for testing"` play? If so, how would something like the `"create result archive filename"` task get access to the value so it can integrate it into the output filename?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/23)_

**Comment by nkinkade** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

_[run.yml, line 16 [r1]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/23#-KJkO8AggSg-HYQL2DWH:-KJlDk9pL7k6fovgwwVT:-1925157518) ([raw file](https://github.com/m-lab/ndt-e2e-ansible/blob/ea935288b5df8a375a492439cf6328a4961ae31c/run.yml#L16)):_
<details><summary>

<i>Previously, mtlynch (Michael Lynch) wrote…</i></summary>



> Right, the thing I'm stuck on is how we share the variable across two separate plays. As far as I know, the only way to do that is by using a variable to create a fact.
> 
> In the solution you're proposing, would `throttle_mbps` be a variable in the `"Configure meddlebox for testing"` play? If so, how would something like the `"create result archive filename"` task get access to the value so it can integrate it into the output filename?
> </details>
> Are variables passed in with `--extra-vars` on the command line not global?  I may be getting confused here.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/23)_

**Comment by mtlynch** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

_[run.yml, line 16 [r1]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/23#-KJkO8AggSg-HYQL2DWH:-KJlE3zRvH5reA8q8cWj:1752004779) ([raw file](https://github.com/m-lab/ndt-e2e-ansible/blob/ea935288b5df8a375a492439cf6328a4961ae31c/run.yml#L16)):_
<details><summary>

<i>Previously, nkinkade wrote…</i></summary>



> Are variables passed in with `--extra-vars` on the command line not global?  I may be getting confused here.
> </details>
> Ah okay that's what I was missing. I didn't realize you were proposing to always use an `--extra-vars` flag.

On the one hand, it makes sense that the user should always have to explicitly choose a bandwidth to test, but on the other hand, it feels a bit confusing to have variables that aren't defined anywhere.

As a workaround, I've added it to `host_vars/meddlebox`. Does that seem reasonable?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/23)_

**Comment by mtlynch** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

_[README.md, line 129 [r1]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/23#-KJlboH2ywr9kansPyOU:-KJlboH2ywr9kansPyOV:-775517757) ([raw file](https://github.com/m-lab/ndt-e2e-ansible/blob/ea935288b5df8a375a492439cf6328a4961ae31c/README.md#L129)):_

> ``` Markdown
>   -l mlab-mac-capitan \
>   --extra-vars "supported_browsers=chrome iterations=50" \
>   --tags "facts,throttle,html5,gather"
> ```

I realized that almost everything would have to have "facts,throttle,gather" as tags so I felt like it made more sense at this point to switch to `--skip-tags`.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/23)_

**Comment by nkinkade** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/23)_

**Comment by nkinkade** [comment]
:lgtm:

<details><summary>

<i>Previously, mtlynch (Michael Lynch) wrote…</i></summary>



> #### Configures throttling as part of perf test run
> 
> Adds commands to explicitly enable packet shaping on the meddlebox before
> 
> every run of the run.yml playbook so that tests run under a defined network
> 
> speed limit.
> 
> Also changes the archive and log name schema so that the meddlebox throttling
> 
> settings are saved as part of the output archive of tests.
> 
> </details>

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/23#-:-KJptXTNjBbokQ7WJALN:1417088721)_

**Pull request merged**
