### PR TITLE
Miscellaneous fixes to Ansible provisioning playbook

### PR DESCRIPTION
**Pull request by mtlynch**
This fixes a few small issues in the provisioning playbook, including:
- Windows
  - Updates the NDT E2E client worker git repository if it already exists
- OS X
  - Fixes an unzip so that it works even if the contents already exist in the destination directory
  - Downloads the Selenium WebDriver extension for Safari
  - Fixes ownership on replay directory and files
- Makes minor changes to task names

---

This change is [Reviewable](https://reviewable.io/reviews/m-lab/ndt-e2e-ansible/6)

### CODE REVIEW

**Comment by nkinkade** [comment]
Notwithstanding one small formatting comment, :lgtm:

<details><summary>

<i>Previously, mtlynch (Michael Lynch) wrote…</i></summary>



> #### Miscellaneous fixes to Ansible provisioning playbook
> 
> This fixes a few small issues in the provisioning playbook, including:
> - Windows
>   - Updates the NDT E2E client worker git repository if it already exists
> - OS X
>   - Fixes an unzip so that it works even if the contents already exist in the destination directory
>   - Downloads the Selenium WebDriver extension for Safari
>   - Fixes ownership on replay directory and files
> - Makes minor changes to task names
> 
> </details>

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[prepare.yml, line 458 [r1]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/6#-KHRTNgvyGqxL45u2vby:-KHRTNgvyGqxL45u2vbz:416560133) ([raw file](https://github.com/m-lab/ndt-e2e-ansible/blob/13723d8cf9902c67c12240e3b22f76675f689aea/prepare.yml#L458)):_

> ``` YAML
>     - name: create HTTP replay directory
>       tags: ndt-e2e
>       file: path={{ http_replay_dir }} state=directory owner={{ ansible_user }}
> ```

To be consistent with the way you done this in other places, would this be cleaner with _state_ and _owner_ on their own lines, indented to align with _path_?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/6#-:-KHRUFEONFKZ1hQJO8cp:417739863)_

**Comment by mtlynch** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[prepare.yml, line 458 [r1]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/6#-KHRTNgvyGqxL45u2vby:-KHRliogeDlTPAvAhRpR:-1969624583) ([raw file](https://github.com/m-lab/ndt-e2e-ansible/blob/13723d8cf9902c67c12240e3b22f76675f689aea/prepare.yml#L458)):_
<details><summary>

<i>Previously, nkinkade wrote…</i></summary>



> To be consistent with the way you done this in other places, would this be cleaner with _state_ and _owner_ on their own lines, indented to align with _path_?</details>
> The pattern I've been trying to follow is that if it fits <= 80 columns on a single line, I do single line and otherwise break it up. Do you have a preference? Maybe we should start an M-Lab Ansible style guide so we just decide these once and that's what we use globally.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/6)_

**Comment by nkinkade** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[prepare.yml, line 458 [r1]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/6#-KHRTNgvyGqxL45u2vby:-KHV1Nth74YRF9_yRZmV:-665178487) ([raw file](https://github.com/m-lab/ndt-e2e-ansible/blob/13723d8cf9902c67c12240e3b22f76675f689aea/prepare.yml#L458)):_
<details><summary>

<i>Previously, mtlynch (Michael Lynch) wrote…</i></summary>



> The pattern I've been trying to follow is that if it fits <= 80 columns on a single line, I do single line and otherwise break it up. Do you have a preference? Maybe we should start an M-Lab Ansible style guide so we just decide these once and that's what we use globally.</details>
> I personally have a preference for indenting each parameter on it's own line, regardless of line length.   It adds a few extra lines to the file, but I believe the readability of it more than makes up for this.  That's just my preference, though, so if you prefer fewer lines at the expense of a very slight decrease in readability, then it's fine to keep it this way. As long as I know that this was done intentionally, and by what criteria, then I can take that into account for future reviews of this sort.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/6)_

**Comment by mtlynch** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[prepare.yml, line 458 [r1]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/6#-KHRTNgvyGqxL45u2vby:-KHVSQf9Te8JMPOKSbUC:-2085608854) ([raw file](https://github.com/m-lab/ndt-e2e-ansible/blob/13723d8cf9902c67c12240e3b22f76675f689aea/prepare.yml#L458)):_
<details><summary>

<i>Previously, nkinkade wrote…</i></summary>



> I personally have a preference for indenting each parameter on it's own line, regardless of line length.   It adds a few extra lines to the file, but I believe the readability of it more than makes up for this.  That's just my preference, though, so if you refer fewer lines at the expense of a very slight decrease in readability, then it's fine to keep it this way. As long as I know that this was done intentionally, and by what criteria, then I can take that into account for future reviews of this sort.</details>
> I think you're right. One parameter per line is a much clearer convention and improves readability. Fixed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/6)_

**Pull request merged**
