### PR TITLE
Adding a provisioning playbook for Windows

### PR DESCRIPTION
**Pull request by mtlynch**
Creating a playbook that sets up Windows machines for NDT E2E testing, including installing all
necessary browsers and dependencies.

---

This change is [Reviewable](https://reviewable.io/reviews/m-lab/ndt-e2e-ansible/1)

### CODE REVIEW

**Comment by nkinkade** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

_[env_path_append.ps1, line 10 [r1]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/1#-KGn4xDdKrGHT3Ho_pHD:-KGn4xDdKrGHT3Ho_pHE:-1894939964) ([raw file](https://github.com/m-lab/ndt-e2e-ansible/blob/f08d3c5f0efc0c7fe30cb861f9d1ce972e2e42b2/env_path_append.ps1#L10)):_
It may not be possible, but it  sure would be nice if we could use [win_environment](http://docs.ansible.com/ansible/win_environment_module.html) for this rather than a special script, but I gather it isn't possible to append to the existing variable with this?

---

_[prepare.yml, line 18 [r1]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/1#-KGmpC6dxkkVpfT39so1:-KGmpC6dxkkVpfT39so2:-1833656200) ([raw file](https://github.com/m-lab/ndt-e2e-ansible/blob/f08d3c5f0efc0c7fe30cb861f9d1ce972e2e42b2/prepare.yml#L18)):_
http://superuser.com/questions/936432/how-do-i-install-a-previous-version-of-chrome ???

---

_[prepare.yml, line 58 [r1]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/1#-KGmpcuRL-baQVEx3tg1:-KGmpcuSQTdNWQtP1UMF:-704447874) ([raw file](https://github.com/m-lab/ndt-e2e-ansible/blob/f08d3c5f0efc0c7fe30cb861f9d1ce972e2e42b2/prepare.yml#L58)):_
You have forward slashes here, and everywhere else backslashes.  Should these be backslashes as well?

---

_[prepare.yml, line 85 [r1]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/1#-KGmqOdsk_BNUP7Z4PiD:-KGmqOdtLnyAmMQDf-n5:-269729183) ([raw file](https://github.com/m-lab/ndt-e2e-ansible/blob/f08d3c5f0efc0c7fe30cb861f9d1ce972e2e42b2/prepare.yml#L85)):_
You have double (escaped?) backslashes everywhere else but here just single backslashes.  Is this something particular to the script command, or should these be double too?

---

_[prepare.yml, line 105 [r1]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/1#-KGmtapCNK8cQPeQGQmI:-KGmtapCNK8cQPeQGQmJ:-666808559) ([raw file](https://github.com/m-lab/ndt-e2e-ansible/blob/f08d3c5f0efc0c7fe30cb861f9d1ce972e2e42b2/prepare.yml#L105)):_
Above you have three separate command blocks for a single package (git). This may be a limitation of the Windows version of Ansible, but on Linux that could (and should) be a single block which check to see if it's installed, if not, downloads it from a URL, and installs it. It seems there is a Windows module named [win_package](http://docs.ansible.com/ansible/win_package_module.html) which is supposed to do something like that.  Could the above be condensed to a single win_package block?  Same goes for Chrome, Firefox, and others below.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/1)_

**Comment by stephen-soltesz** [comment]
Review status: 0 of 2 files reviewed at latest revision, 6 unresolved discussions.

---

_[prepare.yml, line 75 [r1]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/1#-KGn_BdXQCp_hAn_QOHQ:-KGn_BdXQCp_hAn_QOHR:1737697941) ([raw file](https://github.com/m-lab/ndt-e2e-ansible/blob/f08d3c5f0efc0c7fe30cb861f9d1ce972e2e42b2/prepare.yml#L75)):_
Just an idea: are these attributes sensitive to order? I'm wondering if an alternate order might read differently, almost like an imperative program. Would this be helpful?

```
- name download Python
  when not python_binary.stat.exists
  win_get_url:
      proxy_url: "{{ http_proxy }}"
      url: "{{ python_installer.url }}"
      dest: "{{ python_installer.dest }}"
  register: python_download
  tags: python
```

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/1)_

**Comment by mtlynch** [comment]
Review status: 0 of 2 files reviewed at latest revision, 6 unresolved discussions.

---

_[env_path_append.ps1, line 10 [r1]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/1#-KGn4xDdKrGHT3Ho_pHD:-KGr2etPf-RV3_e6EAMs:-477806920) ([raw file](https://github.com/m-lab/ndt-e2e-ansible/blob/f08d3c5f0efc0c7fe30cb861f9d1ce972e2e42b2/env_path_append.ps1#L10)):_
Oof, I spent like 2 hours on this and still can't get it to work. I initially thought this would work:

```
- name: append Python to PATH variable
      tags: python
      win_environment:
          state: present
          name: Path
          value: "{{ ansible_env.Path }};C:\\Python27;C:\\Python27\\Scripts"
          level: machine
      register: python_result
      when: python_install.changed
```

But then I realized that Ansible facts are only evaluated once during setup, so multiple plays that append to `Path` would collide. We could manually refresh `ansible_env.Path`, but then it seems like more trouble than it's worth because we'd need two tasks (append, refresh) every time we want to add to the `Path` environment variable.

---

_[prepare.yml, line 18 [r1]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/1#-KGmpC6dxkkVpfT39so1:-KGr-ubgyw179xKz-x9a:-1335450435) ([raw file](https://github.com/m-lab/ndt-e2e-ansible/blob/f08d3c5f0efc0c7fe30cb861f9d1ce972e2e42b2/prepare.yml#L18)):_
I'm not sure which answer you mean, but it didn't seem like any of those would work for us. The accepted answer is for explicitly choosing an old version of Chromium rather than Chrome (though maybe this is a reason for us to switch to Chromium in the future) and the others get old versions of Chrome from not-so-reputable third-party sources.

---

_[prepare.yml, line 58 [r1]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/1#-KGmpcuRL-baQVEx3tg1:-KGrS6MlBTlQz2vufUUN:-222895990) ([raw file](https://github.com/m-lab/ndt-e2e-ansible/blob/f08d3c5f0efc0c7fe30cb861f9d1ce972e2e42b2/prepare.yml#L58)):_
Ah, I'd misunderstood the example for [win_copy](http://docs.ansible.com/ansible/win_copy_module.html) and thought that it needed forward slashes. Fixed now.

---

_[prepare.yml, line 75 [r1]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/1#-KGn_BdXQCp_hAn_QOHQ:-KGr-Xgc73nlq9IKEViq:1537631180) ([raw file](https://github.com/m-lab/ndt-e2e-ansible/blob/f08d3c5f0efc0c7fe30cb861f9d1ce972e2e42b2/prepare.yml#L75)):_
I agree with the logic, but every playbook I've seen seems to put `when` at the end or near the end, so I think we should stick to what's common for now.

---

_[prepare.yml, line 85 [r1]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/1#-KGmqOdsk_BNUP7Z4PiD:-KGr6Q6GNdh4sPwWBaMN:1278760786) ([raw file](https://github.com/m-lab/ndt-e2e-ansible/blob/f08d3c5f0efc0c7fe30cb861f9d1ce972e2e42b2/prepare.yml#L85)):_
These are deliberately single because if we escape them, they end up as double backslashes when they land in the Windows environment variable. I can't really follow the number of context changes that strings are going through in some of these plays, seems very confusing. Do you think it's worth calling it out explicitly? If it were just one, I would, but it feels tedious to document each one.

---

_[prepare.yml, line 105 [r1]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/1#-KGmtapCNK8cQPeQGQmI:-KGqxRjFjzldt1yL_YWH:-318998286) ([raw file](https://github.com/m-lab/ndt-e2e-ansible/blob/f08d3c5f0efc0c7fe30cb861f9d1ce972e2e42b2/prepare.yml#L105)):_
Oh man, I was really excited about win_package because I had overlooked that module, but I couldn't figure out a way to make it work. I tried this:

``` yaml
    - name: install git
      tags: git
      win_package:
        path=https://github.com/git-for-windows/git/releases/download/v2.8.1.windows.1/Git-2.8.1-64-bit.exe
        product_id="{}"
        arguments="/SILENT"
```

And it fails with:

```
fatal: [win2012-gce-1]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "win_package"}, "msg": "Package from https://github.com/git-for-windows/git/releases/download/v2.8.1.windows.1/Git-2.8.1-64-bit.exe was installed, but the specified ProductId and/or Name does not match package details", "name": "https://github.com/git-for-windows/git/releases/download/v2.8.1.windows.1/Git-2.8.1-64-bit.exe"}
```

Even with verbose logging, it doesn't tell me what it expects the `ProductId` to be, nor can I figure out a way of deducing it from the binary itself. Even after I install all the packages manually and check installed products, it only shows me a product ID for Python:

```
$ ansible win2012-gce-1 -m raw -a "get-wmiobject -class Win32_Product"
win2012-gce-1 | SUCCESS | rc=0 >>


IdentifyingNumber : {16E52445-1392-469F-9ADB-FC03AF00CD61}
Name              : Python 2.7.11
Vendor            : Python Software Foundation
Version           : 2.7.11150
Caption           : Python 2.7.11

IdentifyingNumber : {60EC980A-BDA2-4CB6-A427-B07A5498B4CA}
Name              : Google Update Helper
Vendor            : Google Inc.
Version           : 1.3.29.5
Caption           : Google Update Helper
```

I feel like it might be a function of the fact that `win_package` is still a fairly new and lightly supported module, so things don't work quite right yet.

I started applying it to the Python package, but then I realized `win_package` doesn't seem to support HTTP proxies, which means it breaks in the testbed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/1)_

**Comment by nkinkade** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

_[prepare.yml, line 18 [r1]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/1#-KGmpC6dxkkVpfT39so1:-KGrh3jC21L6oF_HZ-mR:493848323) ([raw file](https://github.com/m-lab/ndt-e2e-ansible/blob/f08d3c5f0efc0c7fe30cb861f9d1ce972e2e42b2/prepare.yml#L18)):_
I was referring to the accepted solution in that question, and thought that if we knew the precise version we wanted in advance that we could download the built version from [commondatastorage.googleapis.com](https://commondatastorage.googleapis.com/chromium-browser-continuous/index.html?prefix=Win_x64/) as needed.  But perhaps the differences between Chromium builds and Chrome releases are enough that we could never rely on them to yield the same results.

---

_[prepare.yml, line 105 [r1]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/1#-KGmtapCNK8cQPeQGQmI:-KGrjOCYnK-wlYJ7xgfP:2030661305) ([raw file](https://github.com/m-lab/ndt-e2e-ansible/blob/f08d3c5f0efc0c7fe30cb861f9d1ce972e2e42b2/prepare.yml#L105)):_
Sorry to send you on a wild goose chase there. I had noticed that the documentation for win_package was pretty sparse, and they gave no clue whatsoever as how to how find the ProductID of any given package.  Thanks for looking into this!

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/1#-:-KGrjl-0swXk0m5SUoyf:1417088721)_

**Comment by mtlynch** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[prepare.yml, line 18 [r1]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/1#-KGmpC6dxkkVpfT39so1:-KGrkQBurreGl3ohSd80:-2127552149) ([raw file](https://github.com/m-lab/ndt-e2e-ansible/blob/f08d3c5f0efc0c7fe30cb861f9d1ce972e2e42b2/prepare.yml#L18)):_
I think it's a good idea long term. I don't think the Chromium vs. Chrome differences will matter to us.

For now, I'd like to finish out M1 just using Chrome, but I've filed:

https://github.com/m-lab/ndt-e2e-ansible/issues/2

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/1)_

**Pull request merged**
