### PR TITLE
Adds a provisioning play for Linux

### PR DESCRIPTION
**Pull request by mtlynch**
Adds an Ansible play for provisioning NDT E2E on Linux client machines.
Configures Linux clients with xvfb, the virtual x11 display server so that
we can run browser tests without an actual output display.

---

This change is [Reviewable](https://reviewable.io/reviews/m-lab/ndt-e2e-ansible/4)

### CODE REVIEW

**Comment by nkinkade** [comment]
Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions.

---

_[prepare.yml, line 266 [r1]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/4#-KH0hfAjl4UA2K2kM6I0:-KH0hfAjl4UA2K2kM6I1:-136327119) ([raw file](https://github.com/m-lab/ndt-e2e-ansible/blob/e221a5092dd2dbe284179c8bd5a6ad927e3516df/prepare.yml#L266)):_
What's the reason for having this block and the following ("install xvfb package") instead of just adding xvfb to the "install apt packages" task?

---

_[prepare.yml, line 285 [r1]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/4#-KH0fwK-GBghlSmwMuzD:-KH0fwK-GBghlSmwMuzE:1957824004) ([raw file](https://github.com/m-lab/ndt-e2e-ansible/blob/e221a5092dd2dbe284179c8bd5a6ad927e3516df/prepare.yml#L285)):_
One the init.d template is installed, would it be possible to use the [service module](http://docs.ansible.com/ansible/service_module.html) to make sure it is always started? The benefit of this is that Ansible can them make sure the service is always started, and not just configure it to start only on boot.

---

_[prepare.yml, line 288 [r1]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/4#-KH0g2y3w6WNoE_0sn3p:-KH0g2y3w6WNoE_0sn3q:-481554121) ([raw file](https://github.com/m-lab/ndt-e2e-ansible/blob/e221a5092dd2dbe284179c8bd5a6ad927e3516df/prepare.yml#L288)):_
Assuming you use the service module to configure xvfb, you can simply set state=started, and this block becomes unnecessary.

---

_[prepare.yml, line 292 [r1]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/4#-KH0gV1JUawr7Ha1xvKj:-KH0gV1JUawr7Ha1xvKk:1570221406) ([raw file](https://github.com/m-lab/ndt-e2e-ansible/blob/e221a5092dd2dbe284179c8bd5a6ad927e3516df/prepare.yml#L292)):_
If you use the apt_repository module for Chrome, then this block should be unnecessary.

---

_[prepare.yml, line 299 [r1]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/4#-KH0edCHLG2kaHQRSg3l:-KH0edCHLG2kaHQRSg3m:1003334999) ([raw file](https://github.com/m-lab/ndt-e2e-ansible/blob/e221a5092dd2dbe284179c8bd5a6ad927e3516df/prepare.yml#L299)):_
Any reason to not use the [apt_key module](http://docs.ansible.com/ansible/apt_key_module.html) here?

---

_[prepare.yml, line 304 [r1]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/4#-KH0emqV6HdVpjbOL5n3:-KH0emqV6HdVpjbOL5n4:-510820339) ([raw file](https://github.com/m-lab/ndt-e2e-ansible/blob/e221a5092dd2dbe284179c8bd5a6ad927e3516df/prepare.yml#L304)):_
Any reason to no use the [apt_repository module](http://docs.ansible.com/ansible/apt_repository_module.html) here?

---

_[prepare.yml, line 311 [r1]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/4#-KH0ezealDyyu5YWGgGE:-KH0ezealDyyu5YWGgGF:-1150002145) ([raw file](https://github.com/m-lab/ndt-e2e-ansible/blob/e221a5092dd2dbe284179c8bd5a6ad927e3516df/prepare.yml#L311)):_
Any reason to not move this to the "apt install packages" task?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/4)_

**Comment by mtlynch** [comment]
Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions.

---

_[prepare.yml, line 266 [r1]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/4#-KH0hfAjl4UA2K2kM6I0:-KH12iF_S2XECahpmJSB:1107564509) ([raw file](https://github.com/m-lab/ndt-e2e-ansible/blob/e221a5092dd2dbe284179c8bd5a6ad927e3516df/prepare.yml#L266)):_
Good point. I was initially thinking we save ourselves a few tasks if it's already installed, but it's easier to just run the tasks no matter what. They're idempotent and not excessively long or anything.

Fixed.

---

_[prepare.yml, line 285 [r1]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/4#-KH0fwK-GBghlSmwMuzD:-KH133OFNckdhxkvm3sr:-1686439438) ([raw file](https://github.com/m-lab/ndt-e2e-ansible/blob/e221a5092dd2dbe284179c8bd5a6ad927e3516df/prepare.yml#L285)):_
Oh, much cleaner. I thought we needed to do `update-rc.d` manually, but I just tried cutting it out and it works as you suggest.

---

_[prepare.yml, line 288 [r1]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/4#-KH0g2y3w6WNoE_0sn3p:-KH13CrBXnX9ba0W-sph:-499146009) ([raw file](https://github.com/m-lab/ndt-e2e-ansible/blob/e221a5092dd2dbe284179c8bd5a6ad927e3516df/prepare.yml#L288)):_
Done.

---

_[prepare.yml, line 292 [r1]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/4#-KH0gV1JUawr7Ha1xvKj:-KH14PSt---UOvvojWn9:-767316376) ([raw file](https://github.com/m-lab/ndt-e2e-ansible/blob/e221a5092dd2dbe284179c8bd5a6ad927e3516df/prepare.yml#L292)):_
Oh, neat. Fixed.

---

_[prepare.yml, line 299 [r1]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/4#-KH0edCHLG2kaHQRSg3l:-KH13y_t7JiiNC4MKI3S:517921094) ([raw file](https://github.com/m-lab/ndt-e2e-ansible/blob/e221a5092dd2dbe284179c8bd5a6ad927e3516df/prepare.yml#L299)):_
Personal ignorance. Fixed!

---

_[prepare.yml, line 304 [r1]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/4#-KH0emqV6HdVpjbOL5n3:-KH14-ZiEqk0ksBusgL9:-1146678810) ([raw file](https://github.com/m-lab/ndt-e2e-ansible/blob/e221a5092dd2dbe284179c8bd5a6ad927e3516df/prepare.yml#L304)):_
Ditto, fixed!

---

_[prepare.yml, line 311 [r1]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/4#-KH0ezealDyyu5YWGgGE:-KH141H4C5hniZ13rM-6:519411381) ([raw file](https://github.com/m-lab/ndt-e2e-ansible/blob/e221a5092dd2dbe284179c8bd5a6ad927e3516df/prepare.yml#L311)):_
Ah, good point. For some reason I felt like the package update has to be first but if we reorder the apt-key stuff, we can do all the apt packages in one shot.

Fixed!

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/4)_

**Comment by nkinkade** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

_[prepare.yml, line 283 [r2]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/4#-KH1MhYhc8XbS6YCe3ne:-KH1MhYiXc6caYkkPD5c:277835788) ([raw file](https://github.com/m-lab/ndt-e2e-ansible/blob/2c35a76f16827324b2336597ccfabfda67bff5d2/prepare.yml#L283)):_
This task may not be necessary, but you check/confirm whether the unarchive module creates missing dirs in the $dest path.

---

_[prepare.yml, line 294 [r2]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/4#-KH1KtHwFLHqPzoEs_l4:-KH1KtHwFLHqPzoEs_l5:-1613103822) ([raw file](https://github.com/m-lab/ndt-e2e-ansible/blob/2c35a76f16827324b2336597ccfabfda67bff5d2/prepare.yml#L294)):_
I don't think this block is necessary.  I believe that the git module in the "download NDT E2E client worker source" task below will automatically create any missing directories in $dest.

---

_[prepare.yml, line 315 [r2]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/4#-KH1MHKuNGCbu_w9m-tZ:-KH1MHKuNGCbu_w9m-t_:372540348) ([raw file](https://github.com/m-lab/ndt-e2e-ansible/blob/2c35a76f16827324b2336597ccfabfda67bff5d2/prepare.yml#L315)):_
Similarly, I don't believe this task is necessary.  I think the copy module will automatically create any missing directories in the $dest path in "copy HTTP  replay" below.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/4)_

**Comment by mtlynch** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

_[prepare.yml, line 283 [r2]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/4#-KH1MhYhc8XbS6YCe3ne:-KH1Q8wsQDnrY46pPyY9:1203772969) ([raw file](https://github.com/m-lab/ndt-e2e-ansible/blob/2c35a76f16827324b2336597ccfabfda67bff5d2/prepare.yml#L283)):_
I think this is a no-go. Tried it and got:

> FAILED! => {"changed": false, "failed": true, "msg": "dest '/opt/selenium_drivers' must be an existing dir"}

---

_[prepare.yml, line 294 [r2]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/4#-KH1KtHwFLHqPzoEs_l4:-KH1OoNj05UTKB3x_afU:1318053742) ([raw file](https://github.com/m-lab/ndt-e2e-ansible/blob/2c35a76f16827324b2336597ccfabfda67bff5d2/prepare.yml#L294)):_
Oh, this is a permissions issue. We can't write to `/opt` unless we're root. The git module doesn't seem to let you declare an owner of the files. What do you think makes sense here?

---

_[prepare.yml, line 315 [r2]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/4#-KH1MHKuNGCbu_w9m-tZ:-KH1PBU3dbZ4_djkG92G:-62807611) ([raw file](https://github.com/m-lab/ndt-e2e-ansible/blob/2c35a76f16827324b2336597ccfabfda67bff5d2/prepare.yml#L315)):_
Ah, true. This was also a permissions issue, but we can run `copy` as root and then just transfer ownership to `ansible_user`. Fixed!

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/4)_

**Comment by nkinkade** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/4#-:-KH1TkGbpi_xlyLieMZq:1417088721)_

**Pull request merged**
