### PR TITLE
Adding M-Lab testbed configuration details

### PR DESCRIPTION
**Pull request by mtlynch**
Adding configuration details for the M-Lab testbed.
Adds a README that documents how to use the ansible playbooks to manage tasks
in the testbed.

---

This change is [Reviewable](https://reviewable.io/reviews/m-lab/ndt-e2e-ansible/8)

### CODE REVIEW

**Comment by salarcon215** [comment]
Reviewed 1 of 4 files at r1.
Review status: 1 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

_[configure_control.yml, line 3 [r1]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/8#-KHdOA-0MVRZxX0y4P22:-KHdOA-1nAqkzuch0oV5:-892475642) ([raw file](https://github.com/m-lab/ndt-e2e-ansible/blob/d6ea855bf29dba7e09663100013c90e5ac416cb0/configure_control.yml#L3)):_

> ``` YAML
> ---
> # vim:ft=ansible:
> ```

Is this comment a note to anyone modifying the file prompting them to use that vim setting for clean formatting? Can we make that explicit in a few words?

# Please use this vim setting to ensure compliant formatting.

# vim:ft=ansible:

---

_[configure_control.yml, line 21 [r1]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/8#-KHdaZMoIMzwXpBqEzTn:-KHdaZMoIMzwXpBqEzTo:-888597314) ([raw file](https://github.com/m-lab/ndt-e2e-ansible/blob/d6ea855bf29dba7e09663100013c90e5ac416cb0/configure_control.yml#L21)):_

> ``` YAML
>           172.16.1.31        mlab-wdoze7
>           172.16.1.32        mlab-wdoze8
>           172.16.1.33        mlab-wdoze10
> ```

Chris is changing the windows hostnames very soon. Do you prefer to wait for that, or to merge changes then make a new PR once Chris is done?

---

_[hosts, line 2 [r1]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/8#-KHdat6VO-N5RStQjhXJ:-KHdat6VO-N5RStQjhXK:1835253689) ([raw file](https://github.com/m-lab/ndt-e2e-ansible/blob/d6ea855bf29dba7e09663100013c90e5ac416cb0/hosts#L2)):_

> ```
> [windows]
> mlab-wdoze10
> ```

Same note on changing hostnames.

---

_[README.md, line 2 [r1]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/8#-KHdi0ubJLkhh-qiJr3G:-KHdi0ucP0fT8ASaZ6nm:-985782391) ([raw file](https://github.com/m-lab/ndt-e2e-ansible/blob/d6ea855bf29dba7e09663100013c90e5ac416cb0/README.md#L2)):_

> ``` Markdown
> # ndt-e2e-ansible
> Ansible playbooks for NDT E2E Testing system
> ```

Mo' flava text please, something like:
These playbooks automate the configuration of nodes and execution of tests required to perform automated end-to-end testing of NDT.  

Node configs include:
- Control node - A machine that coordinates testing (runs on <operator's local machine>|<a particular server> | < a server image hosted _here_> )
-  Testbed client worker nodes - Sets up the testbed client machines. Contains options to set up all at once, or individual machines

Test execution options include:
- Run a single test or multiple tests
- Run against a single client node or multiple client nodes
- Run against specific client conditions such as NDT client type or client node browser version

---

_[README.md, line 16 [r1]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/8#-KHdhh4kwSKFdkjy5YLF:-KHdhh4kwSKFdkjy5YLG:1333876263) ([raw file](https://github.com/m-lab/ndt-e2e-ansible/blob/d6ea855bf29dba7e09663100013c90e5ac416cb0/README.md#L16)):_

> ``` Markdown
> 
> To configure the control node to manage the machines in the testbed, run the
> following command:
> ```

Can you describe the control node? Is this generally the operator's local machine, or are we using a specific server or server image?

---

_[README.md, line 28 [r1]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/8#-KHdlZQWkDlcKkb0nCFi:-KHdlZQXK1NGADdB8aqi:1568674202) ([raw file](https://github.com/m-lab/ndt-e2e-ansible/blob/d6ea855bf29dba7e09663100013c90e5ac416cb0/README.md#L28)):_

> `````` Markdown
> 
> ```bash
> ansible-playbook prepare.yml
> ``````

I don't love the filenames prepare.yml and run.yml because they are way ambiguous, but I appreciate that there's value in keeping them short for ease of typing. Maybe in the context of the location of the Ansible files, the intent of the scripts will be clear, maybe something like run-e2e.yml is better. What's your thought?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/8)_

**Comment by mtlynch** [comment]
Review status: 1 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

_[configure_control.yml, line 3 [r1]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/8#-KHdOA-0MVRZxX0y4P22:-KHefyStDz0kTcTintCD:1954206964) ([raw file](https://github.com/m-lab/ndt-e2e-ansible/blob/d6ea855bf29dba7e09663100013c90e5ac416cb0/configure_control.yml#L3)):_
<details><summary>

<i>Previously, salarcon215 wrote…</i></summary>



> Is this comment a note to anyone modifying the file prompting them to use that vim setting for clean formatting? Can we make that explicit in a few words?
> 
> # Please use this vim setting to ensure compliant formatting.
> 
> # vim:ft=ansible:</details>
> 
> These are [Vim modelines](http://vim.wikia.com/wiki/Modeline_magic), so they're instructions to Vim rather than to humans.

I've added an issue to our style guide about whether we want to allow/require these universally: https://github.com/m-lab/ansible-style-guide/issues/7

---

_[configure_control.yml, line 21 [r1]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/8#-KHdaZMoIMzwXpBqEzTn:-KHeh0pWKrV2reEEE0k4:1067569391) ([raw file](https://github.com/m-lab/ndt-e2e-ansible/blob/d6ea855bf29dba7e09663100013c90e5ac416cb0/configure_control.yml#L21)):_
<details><summary>

<i>Previously, salarcon215 wrote…</i></summary>



> Chris is changing the windows hostnames very soon. Do you prefer to wait for that, or to merge changes then make a new PR once Chris is done?</details>
> I'd prefer to just get it in now and make the minor change after the rename. I'm going to be using this `hosts` file in its current form to do performance validation of the current NDT rollout, so it feels right to have that checked in at the time of testing.

---

_[hosts, line 2 [r1]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/8#-KHdat6VO-N5RStQjhXJ:-KHehDKfjkpbpfvjK1JA:-1315183157) ([raw file](https://github.com/m-lab/ndt-e2e-ansible/blob/d6ea855bf29dba7e09663100013c90e5ac416cb0/hosts#L2)):_
<details><summary>

<i>Previously, salarcon215 wrote…</i></summary>



> Same note on changing hostnames.</details>
> ditto here

---

_[README.md, line 2 [r1]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/8#-KHdi0ubJLkhh-qiJr3G:-KHemY3_B2aoNSqQw8A0:-281193678) ([raw file](https://github.com/m-lab/ndt-e2e-ansible/blob/d6ea855bf29dba7e09663100013c90e5ac416cb0/README.md#L2)):_
<details><summary>

<i>Previously, salarcon215 wrote…</i></summary>



> Mo' flava text please, something like:
> These playbooks automate the configuration of nodes and execution of tests required to perform automated end-to-end testing of NDT.  
> 
> Node configs include:
> - Control node - A machine that coordinates testing (runs on <operator's local machine>|<a particular server> | < a server image hosted _here_> )
> -  Testbed client worker nodes - Sets up the testbed client machines. Contains options to set up all at once, or individual machines
> 
> Test execution options include:
> - Run a single test or multiple tests
> - Run against a single client node or multiple client nodes
> - Run against specific client conditions such as NDT client type or client node browser version</details>
>   Good idea. Updated based on your suggestions. I want to de-emphasize the "single node vs. multiple nodes" because that's inherently true of Ansible but I think it's a good idea to cover what groupings we support.

---

_[README.md, line 16 [r1]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/8#-KHdhh4kwSKFdkjy5YLF:-KHejUN5DXTMgwLy_bA6:1590107987) ([raw file](https://github.com/m-lab/ndt-e2e-ansible/blob/d6ea855bf29dba7e09663100013c90e5ac416cb0/README.md#L16)):_
<details><summary>

<i>Previously, salarcon215 wrote…</i></summary>



> Can you describe the control node? Is this generally the operator's local machine, or are we using a specific server or server image?</details>
> I was trying to match Ansible's semantics:

http://docs.ansible.com/ansible/intro_installation.html#control-machine-requirements

But now that you mention it, this should be control _machine_ rather than control _node_ because I think in Ansible terms, "nodes" are generally the remote machines we're controlling, so "control node" might be contradictory. I've updated the text to fix this.

We don't make any assumptions about the control machine other than what's described in the pre-reqs. Are there other details you think might be helpful to include here?

---

_[README.md, line 28 [r1]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/8#-KHdlZQWkDlcKkb0nCFi:-KHeipMoQeV-5GSANSvQ:-202579522) ([raw file](https://github.com/m-lab/ndt-e2e-ansible/blob/d6ea855bf29dba7e09663100013c90e5ac416cb0/README.md#L28)):_
<details><summary>

<i>Previously, salarcon215 wrote…</i></summary>



> I don't love the filenames prepare.yml and run.yml because they are way ambiguous, but I appreciate that there's value in keeping them short for ease of typing. Maybe in the context of the location of the Ansible files, the intent of the scripts will be clear, maybe something like run-e2e.yml is better. What's your thought?</details>
> That's a good point. I just wrote them as temporary placeholders when I started creating them and never gave them careful thought. I think renaming them is outside the scope of this PR, but I filed https://github.com/m-lab/ndt-e2e-ansible/issues/9.

The short filenames aren't intentional or important to me because I just use bash auto-completion all the time anyway, so longer names are fine from my perspective. How do you feel about the proposed names in the bug?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/8)_

**Comment by salarcon215** [comment]
Review status: 1 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

_[configure_control.yml, line 3 [r1]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/8#-KHdOA-0MVRZxX0y4P22:-KHfLD0VOCn7G4-yy-V2:-1613438801) ([raw file](https://github.com/m-lab/ndt-e2e-ansible/blob/d6ea855bf29dba7e09663100013c90e5ac416cb0/configure_control.yml#L3)):_
<details><summary>

<i>Previously, mtlynch (Michael Lynch) wrote…</i></summary>



> These are [Vim modelines](http://vim.wikia.com/wiki/Modeline_magic), so they're instructions to Vim rather than to humans.
> 
> I've added an issue to our style guide about whether we want to allow/require these universally: https://github.com/m-lab/ansible-style-guide/issues/7</details>
> Ok. I'm giving it a thumbs up. Let's do a new PR if the result of the discussion in the style guide is to use a different method of vim signaling. 

---

_[README.md, line 16 [r1]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/8#-KHdhh4kwSKFdkjy5YLF:-KHfMcq5tU9Vy7fKI3P2:-1556616055) ([raw file](https://github.com/m-lab/ndt-e2e-ansible/blob/d6ea855bf29dba7e09663100013c90e5ac416cb0/README.md#L16)):_
<details><summary>

<i>Previously, mtlynch (Michael Lynch) wrote…</i></summary>



> I was trying to match Ansible's semantics:
> 
> http://docs.ansible.com/ansible/intro_installation.html#control-machine-requirements
> 
> But now that you mention it, this should be control _machine_ rather than control _node_ because I think in Ansible terms, "nodes" are generally the remote machines we're controlling, so "control node" might be contradictory. I've updated the text to fix this.
> 
> We don't make any assumptions about the control machine other than what's described in the pre-reqs. Are there other details you think might be helpful to include here?</details>
> A short sentence on what "control machine" means in Ansible--and therefore this e2e test--would satisfy me. Or an example, like how you set up and used your devel machine, or whatever you used in real life to try this out.

---

_[README.md, line 28 [r1]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/8#-KHdlZQWkDlcKkb0nCFi:-KHfMvXoIexUvwRDpdn8:-653277495) ([raw file](https://github.com/m-lab/ndt-e2e-ansible/blob/d6ea855bf29dba7e09663100013c90e5ac416cb0/README.md#L28)):_
<details><summary>

<i>Previously, mtlynch (Michael Lynch) wrote…</i></summary>



> That's a good point. I just wrote them as temporary placeholders when I started creating them and never gave them careful thought. I think renaming them is outside the scope of this PR, but I filed https://github.com/m-lab/ndt-e2e-ansible/issues/9.
> 
> The short filenames aren't intentional or important to me because I just use bash auto-completion all the time anyway, so longer names are fine from my perspective. How do you feel about the proposed names in the bug?</details>
> The filenames you proposed are great, thank you.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/8)_

**Comment by mtlynch** [comment]
Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

_[README.md, line 16 [r1]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/8#-KHdhh4kwSKFdkjy5YLF:-KHfPkOwijczwPP0Lfsw:1130407093) ([raw file](https://github.com/m-lab/ndt-e2e-ansible/blob/d6ea855bf29dba7e09663100013c90e5ac416cb0/README.md#L16)):_
<details><summary>

<i>Previously, salarcon215 wrote…</i></summary>



> A short sentence on what "control machine" means in Ansible--and therefore this e2e test--would satisfy me. Or an example, like how you set up and used your devel machine, or whatever you used in real life to try this out.</details>
> Cool, updated.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/8)_

**Comment by salarcon215** [comment]
Reviewed 2 of 4 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/8)_

**Comment by salarcon215** [comment]
:lgtm:

<details><summary>

<i>Previously, mtlynch (Michael Lynch) wrote…</i></summary>



> #### Adding M-Lab testbed configuration details
> 
> Adding configuration details for the M-Lab testbed.
> 
> Adds a README that documents how to use the ansible playbooks to manage tasks
> 
> in the testbed.
> 
> </details>

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt-e2e-ansible/8#-:-KHfUrzwpndBix7ylhUq:1417088721)_

**Pull request merged**
